// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class AspNetRoleClaim : BaseEntity
{
 
    public string RoleId { get; set; }

    public string ClaimType { get; set; }

    public string ClaimValue { get; set; }

    public virtual AspNetRole Role { get; set; }
}