// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class AspNetRole : BaseEntity
{


    public string Name { get; set; }

    public string NormalizedName { get; set; }

    public string ConcurrencyStamp { get; set; }

    public virtual ICollection<AspNetRoleClaim> AspNetRoleClaims { get; set; } = new List<AspNetRoleClaim>();

    public virtual ICollection<UserPracticeInvitation> UserPracticeInvitations { get; set; } = new List<UserPracticeInvitation>();

    public virtual ICollection<UserPracticeRole> UserPracticeRoles { get; set; } = new List<UserPracticeRole>();

    public virtual ICollection<AspNetUser> Users { get; set; } = new List<AspNetUser>();
}