// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class BillingSummary : BaseEntity
{
    public Guid PracticeId { get; set; }

    public Guid ClientId { get; set; }

    public string ClientName { get; set; }

    public decimal? ArCurrent { get; set; }

    public decimal? Ar30 { get; set; }

    public decimal? Ar60 { get; set; }

    public decimal? Ar90 { get; set; }

    public decimal? TotalDue { get; set; }

    public decimal CreditLimit { get; set; }

    public DateTime? LastPayDate { get; set; }

    public decimal? LastPayAmt { get; set; }

    public int? OpenInvoiceCount { get; set; }

    public int? RecentInvoiceCount { get; set; }

    public string BillingStatus { get; set; }
}