// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class Client : BaseEntity
{
    public Guid ClientId { get; set; }

    public Guid PracticeId { get; set; }

    public string ClientAccountNumber { get; set; }

    public string ClientName { get; set; }

    public string BillingStatus { get; set; }

    public decimal CreditLimit { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Practice Practice { get; set; }

    public virtual ICollection<Principal> Principals { get; set; } = new List<Principal>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}