// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

//^(\s*public\s+partial\s+class\s+[A-Za-z_]\w*)(?!\s*:)

public partial class Invoice : BaseEntity
{
    public Guid InvoiceId { get; set; }

    public Guid PracticeId { get; set; }

    public Guid ClientId { get; set; }

    public string InvoiceNumber { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public DateOnly DueDate { get; set; }

    public string StatusName { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal BalanceAmount { get; set; }

    public bool IsOpen { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Source { get; set; }

    public virtual Client Client { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Practice Practice { get; set; }

    public virtual InvoiceStatusLookup StatusNameNavigation { get; set; }
}