// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SlickSysDev.ApiService.Model;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SlickSysDev.ApiService.Model
{
    public partial interface ISlickSysDevContextProcedures
    {
        Task<List<usp_accept_user_practice_invitationResult>> usp_accept_user_practice_invitationAsync(Guid? invite_token, string accepted_user_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_add_user_practice_roleResult>> usp_add_user_practice_roleAsync(Guid? practice_id, string user_id, string role_name, DateTime? expires_at, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_authorize_user_practiceResult>> usp_authorize_user_practiceAsync(Guid? practice_id, string user_id, string required_role_name, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_billing_summary_countResult>> usp_billing_summary_countAsync(Guid? practice_id, Guid? client_id, string billing_status, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_billing_summary_pagedResult>> usp_billing_summary_pagedAsync(Guid? practice_id, Guid? client_id, string billing_status, int? offset_rows, int? fetch_rows, bool? sort_desc, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_create_appointmentResult>> usp_create_appointmentAsync(Guid? practice_id, Guid? client_id, Guid? principal_id, Guid? resource_id, Guid? status_id, DateTime? start_time, DateTime? end_time, string comments, Guid? group_id, Guid? recurrence_id, string source, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_create_reservationResult>> usp_create_reservationAsync(Guid? practice_id, Guid? client_id, Guid? principal_id, DateTime? arrival_date, DateTime? ending_date, Guid? status_id, Guid? visual_status_id, bool? hospitalized_flag, string comments, string source, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_create_user_practice_invitationResult>> usp_create_user_practice_invitationAsync(Guid? practice_id, string role_name, string email, string invited_by_user_id, DateTime? expires_at, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_post_paymentResult>> usp_post_paymentAsync(Guid? practice_id, Guid? client_id, Guid? invoice_id, decimal? payment_amount, DateTime? payment_date, string payment_method, string reference_number, string memo, string source, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_practice_invitations_countResult>> usp_practice_invitations_countAsync(Guid? practice_id, string status_name, string role_name, string search_text, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_practice_invitations_pagedResult>> usp_practice_invitations_pagedAsync(Guid? practice_id, string status_name, string role_name, string search_text, int? offset_rows, int? fetch_rows, bool? sort_desc, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_practice_users_countResult>> usp_practice_users_countAsync(Guid? practice_id, string role_name, bool? active_only, string search_text, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_practice_users_pagedResult>> usp_practice_users_pagedAsync(Guid? practice_id, string role_name, bool? active_only, string search_text, int? offset_rows, int? fetch_rows, bool? sort_desc, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_principal_summary_countResult>> usp_principal_summary_countAsync(Guid? practice_id, Guid? client_id, Guid? principal_id, string context_label, bool? active, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_principal_summary_pagedResult>> usp_principal_summary_pagedAsync(Guid? practice_id, Guid? client_id, Guid? principal_id, string context_label, bool? active, int? offset_rows, int? fetch_rows, bool? sort_desc, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_remove_user_practice_roleResult>> usp_remove_user_practice_roleAsync(Guid? practice_id, string user_id, string role_name, DateTime? expires_at, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_revoke_user_practice_invitationResult>> usp_revoke_user_practice_invitationAsync(Guid? invite_token, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_schedule_board_countResult>> usp_schedule_board_countAsync(Guid? practice_id, DateTime? from_time, DateTime? to_time, Guid? client_id, Guid? principal_id, Guid? status_id, string item_type, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_schedule_board_pagedResult>> usp_schedule_board_pagedAsync(Guid? practice_id, DateTime? from_time, DateTime? to_time, Guid? client_id, Guid? principal_id, Guid? status_id, string item_type, int? offset_rows, int? fetch_rows, bool? sort_desc, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_update_appointmentResult>> usp_update_appointmentAsync(Guid? practice_id, Guid? appointment_id, Guid? status_id, Guid? resource_id, DateTime? start_time, DateTime? end_time, string comments, bool? is_deleted, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_update_reservationResult>> usp_update_reservationAsync(Guid? practice_id, Guid? reservation_id, Guid? status_id, Guid? visual_status_id, DateTime? arrival_date, DateTime? ending_date, bool? hospitalized_flag, string comments, bool? is_deleted, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_user_practices_countResult>> usp_user_practices_countAsync(string user_id, string role_name, bool? active_only, string search_text, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_user_practices_pagedResult>> usp_user_practices_pagedAsync(string user_id, string role_name, bool? active_only, string search_text, int? offset_rows, int? fetch_rows, bool? sort_desc, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
