// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class Payment : BaseEntity
{
    public Guid PaymentId { get; set; }

    public Guid PracticeId { get; set; }

    public Guid ClientId { get; set; }

    public Guid? InvoiceId { get; set; }

    public decimal PaymentAmount { get; set; }

    public DateTime PaymentDate { get; set; }

    public string PaymentMethod { get; set; }

    public string ReferenceNumber { get; set; }

    public string Memo { get; set; }

    public string Source { get; set; }

    public DateTime PostedAt { get; set; }

    public virtual Client Client { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual PaymentMethod PaymentMethodNavigation { get; set; }

    public virtual Practice Practice { get; set; }
}