// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class Practice : BaseEntity
{
    public Guid PracticeId { get; set; }

    public string PracticeName { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<AppointmentStatus> AppointmentStatuses { get; set; } = new List<AppointmentStatus>();

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Principal> Principals { get; set; } = new List<Principal>();

    public virtual ICollection<ReservationStatus> ReservationStatuses { get; set; } = new List<ReservationStatus>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<Resource> Resources { get; set; } = new List<Resource>();

    public virtual ICollection<UserPracticeInvitation> UserPracticeInvitations { get; set; } = new List<UserPracticeInvitation>();

    public virtual ICollection<UserPracticeRole> UserPracticeRoles { get; set; } = new List<UserPracticeRole>();
}