// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class PrincipalContextLabel : BaseEntity
{
    public string ContextLabel { get; set; }

    public string DisplayName { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Principal> Principals { get; set; } = new List<Principal>();
}