// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class Principal : BaseEntity
{
    public Guid PrincipalId { get; set; }

    public Guid PracticeId { get; set; }

    public Guid ClientId { get; set; }

    public string DisplayName { get; set; }

    public string ContextLabel { get; set; }

    public string Species { get; set; }

    public string Breed { get; set; }

    public string Sex { get; set; }

    public DateOnly? Birthdate { get; set; }

    public bool Active { get; set; }

    public DateTime? LatestVisit { get; set; }

    public string Flags { get; set; }

    public string PreventiveFlags { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Client Client { get; set; }

    public virtual PrincipalContextLabel ContextLabelNavigation { get; set; }

    public virtual Practice Practice { get; set; }

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}