// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class PrincipalSummary : BaseEntity
{
    public Guid PracticeId { get; set; }

    public Guid PrincipalId { get; set; }

    public Guid ClientId { get; set; }

    public string ClientAccountNumber { get; set; }

    public string ClientName { get; set; }

    public string DisplayName { get; set; }

    public string ContextLabel { get; set; }

    public string Species { get; set; }

    public string Breed { get; set; }

    public string Sex { get; set; }

    public DateOnly? Birthdate { get; set; }

    public bool Active { get; set; }

    public DateTime? LatestVisit { get; set; }

    public string Flags { get; set; }

    public string PreventiveFlags { get; set; }
}