// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class ReservationStatus : BaseEntity
{
    public Guid StatusId { get; set; }

    public Guid PracticeId { get; set; }

    public string StatusName { get; set; }

    public int SortOrder { get; set; }

    public bool IsActive { get; set; }

    public string ColorCode { get; set; }

    public virtual Practice Practice { get; set; }

    public virtual ICollection<Reservation> ReservationStatuses { get; set; } = new List<Reservation>();

    public virtual ICollection<Reservation> ReservationVisualStatuses { get; set; } = new List<Reservation>();
}