// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class Reservation : BaseEntity
{
    public Guid ReservationId { get; set; }

    public Guid PracticeId { get; set; }

    public Guid ClientId { get; set; }

    public Guid? PrincipalId { get; set; }

    public DateTime ArrivalDate { get; set; }

    public DateTime EndingDate { get; set; }

    public Guid StatusId { get; set; }

    public Guid? VisualStatusId { get; set; }

    public bool HospitalizedFlag { get; set; }

    public string Comments { get; set; }

    public string Source { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Client Client { get; set; }

    public virtual Practice Practice { get; set; }

    public virtual Principal Principal { get; set; }

    public virtual ReservationStatus Status { get; set; }

    public virtual ReservationStatus VisualStatus { get; set; }
}