// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class Resource : BaseEntity
{
    public Guid ResourceId { get; set; }

    public Guid PracticeId { get; set; }

    public string ResourceName { get; set; }

    public string ResourceType { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual Practice Practice { get; set; }

    public virtual ResourceType ResourceTypeNavigation { get; set; }
}