// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class ResourceType : BaseEntity
{
    public string ResourceType1 { get; set; }

    public string DisplayName { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Resource> Resources { get; set; } = new List<Resource>();
}