// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class ScheduleBoard : BaseEntity
{
    public Guid PracticeId { get; set; }

    public Guid? AppointmentId { get; set; }

    public Guid? ReservationId { get; set; }

    public Guid ClientId { get; set; }

    public Guid? PrincipalId { get; set; }

    public Guid? ResourceId { get; set; }

    public string ResourceName { get; set; }

    public string ResourceType { get; set; }

    public Guid StatusId { get; set; }

    public string StatusName { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Comments { get; set; }

    public Guid? GroupId { get; set; }

    public Guid? RecurrenceId { get; set; }

    public bool IsDeleted { get; set; }

    public string ItemType { get; set; }
}