// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SlickSysDev.ApiService.Model;

public partial class SlickSysDevContex : DbContext
{
    public SlickSysDevContext()
    {
    }

    public SlickSysDevContext(DbContextOptions<SlickSysDevContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<AppointmentStatus> AppointmentStatuses { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<BillingSummary> BillingSummaries { get; set; }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<InvoiceStatusLookup> InvoiceStatusLookups { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Practice> Practices { get; set; }

    public virtual DbSet<Principal> Principals { get; set; }

    public virtual DbSet<PrincipalContextLabel> PrincipalContextLabels { get; set; }

    public virtual DbSet<PrincipalSummary> PrincipalSummaries { get; set; }

    public virtual DbSet<Reservation> Reservations { get; set; }

    public virtual DbSet<ReservationStatus> ReservationStatuses { get; set; }

    public virtual DbSet<Resource> Resources { get; set; }

    public virtual DbSet<ResourceType> ResourceTypes { get; set; }

    public virtual DbSet<ScheduleBoard> ScheduleBoards { get; set; }

    public virtual DbSet<UserPracticeAccess> UserPracticeAccesses { get; set; }

    public virtual DbSet<UserPracticeInvitation> UserPracticeInvitations { get; set; }

    public virtual DbSet<UserPracticeRole> UserPracticeRoles { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\ProjectModels;Initial Catalog=managementdata_e2e;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Appointment>(entity =>
        {
            entity.HasKey(e => e.AppointmentId).HasName("pk_appointment");

            entity.ToTable("appointment");

            entity.HasIndex(e => new { e.ClientId, e.PrincipalId }, "ix_appointment_client_principal");

            entity.HasIndex(e => new { e.PracticeId, e.StartTime }, "ix_appointment_practice_start_time");

            entity.Property(e => e.AppointmentId)
                .HasDefaultValueSql("(newid())", "df_appointment_appointment_id")
                .HasColumnName("appointment_id");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.Comments)
                .HasMaxLength(2000)
                .HasColumnName("comments");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_appointment_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.EndTime)
                .HasPrecision(0)
                .HasColumnName("end_time");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.PrincipalId).HasColumnName("principal_id");
            entity.Property(e => e.RecurrenceId).HasColumnName("recurrence_id");
            entity.Property(e => e.ResourceId).HasColumnName("resource_id");
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("new", "df_appointment_source")
                .HasColumnName("source");
            entity.Property(e => e.StartTime)
                .HasPrecision(0)
                .HasColumnName("start_time");
            entity.Property(e => e.StatusId).HasColumnName("status_id");

            entity.HasOne(d => d.Client).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_appointment_client");

            entity.HasOne(d => d.Practice).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_appointment_practice");

            entity.HasOne(d => d.Principal).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.PrincipalId)
                .HasConstraintName("fk_appointment_principal");

            entity.HasOne(d => d.Resource).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.ResourceId)
                .HasConstraintName("fk_appointment_resource");

            entity.HasOne(d => d.Status).WithMany(p => p.Appointments)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_appointment_status");
        });

        modelBuilder.Entity<AppointmentStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("pk_appointment_status");

            entity.ToTable("appointment_status");

            entity.Property(e => e.StatusId)
                .HasDefaultValueSql("(newid())", "df_appointment_status_status_id")
                .HasColumnName("status_id");
            entity.Property(e => e.ColorCode)
                .HasMaxLength(20)
                .HasColumnName("color_code");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_appointment_status_is_active")
                .HasColumnName("is_active");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.SortOrder).HasColumnName("sort_order");
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("status_name");

            entity.HasOne(d => d.Practice).WithMany(p => p.AppointmentStatuses)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_appointment_status_practice");
        });

        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Roles).WithMany(p => p.Users)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRole",
                    r => r.HasOne<AspNetRole>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUser>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.ToTable("AspNetUserRoles");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<BillingSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("billing_summary");

            entity.Property(e => e.Ar30)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("ar_30");
            entity.Property(e => e.Ar60)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("ar_60");
            entity.Property(e => e.Ar90)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("ar_90");
            entity.Property(e => e.ArCurrent)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("ar_current");
            entity.Property(e => e.BillingStatus)
                .IsRequired()
                .HasMaxLength(8)
                .HasColumnName("billing_status");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.ClientName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("client_name");
            entity.Property(e => e.CreditLimit)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("credit_limit");
            entity.Property(e => e.LastPayAmt)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("last_pay_amt");
            entity.Property(e => e.LastPayDate)
                .HasPrecision(0)
                .HasColumnName("last_pay_date");
            entity.Property(e => e.OpenInvoiceCount).HasColumnName("open_invoice_count");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.RecentInvoiceCount).HasColumnName("recent_invoice_count");
            entity.Property(e => e.TotalDue)
                .HasColumnType("decimal(38, 2)")
                .HasColumnName("total_due");
        });

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.ClientId).HasName("pk_client");

            entity.ToTable("client");

            entity.HasIndex(e => new { e.PracticeId, e.ClientAccountNumber }, "ux_client_practice_account_number").IsUnique();

            entity.Property(e => e.ClientId)
                .HasDefaultValueSql("(newid())", "df_client_client_id")
                .HasColumnName("client_id");
            entity.Property(e => e.BillingStatus)
                .HasMaxLength(50)
                .HasColumnName("billing_status");
            entity.Property(e => e.ClientAccountNumber)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("client_account_number");
            entity.Property(e => e.ClientName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("client_name");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_client_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.CreditLimit)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("credit_limit");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_client_is_active")
                .HasColumnName("is_active");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");

            entity.HasOne(d => d.Practice).WithMany(p => p.Clients)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_client_practice");
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.InvoiceId).HasName("pk_invoice");

            entity.ToTable("invoice");

            entity.HasIndex(e => new { e.PracticeId, e.ClientId, e.InvoiceDate }, "ix_invoice_practice_client_date");

            entity.Property(e => e.InvoiceId)
                .HasDefaultValueSql("(newid())", "df_invoice_invoice_id")
                .HasColumnName("invoice_id");
            entity.Property(e => e.BalanceAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("balance_amount");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_invoice_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.DueDate).HasColumnName("due_date");
            entity.Property(e => e.InvoiceDate).HasColumnName("invoice_date");
            entity.Property(e => e.InvoiceNumber)
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnName("invoice_number");
            entity.Property(e => e.IsOpen)
                .HasDefaultValue(true, "df_invoice_is_open")
                .HasColumnName("is_open");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("new", "df_invoice_source")
                .HasColumnName("source");
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status_name");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_amount");

            entity.HasOne(d => d.Client).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_invoice_client");

            entity.HasOne(d => d.Practice).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_invoice_practice");

            entity.HasOne(d => d.StatusNameNavigation).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.StatusName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_invoice_invoice_status");
        });

        modelBuilder.Entity<InvoiceStatusLookup>(entity =>
        {
            entity.HasKey(e => e.InvoiceStatus).HasName("pk_invoice_status_lookup");

            entity.ToTable("invoice_status_lookup");

            entity.Property(e => e.InvoiceStatus)
                .HasMaxLength(50)
                .HasColumnName("invoice_status");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("display_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_invoice_status_lookup_is_active")
                .HasColumnName("is_active");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("pk_payment");

            entity.ToTable("payment");

            entity.HasIndex(e => new { e.ClientId, e.PaymentDate }, "ix_payment_client_date");

            entity.Property(e => e.PaymentId)
                .HasDefaultValueSql("(newid())", "df_payment_payment_id")
                .HasColumnName("payment_id");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.InvoiceId).HasColumnName("invoice_id");
            entity.Property(e => e.Memo)
                .HasMaxLength(400)
                .HasColumnName("memo");
            entity.Property(e => e.PaymentAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("payment_amount");
            entity.Property(e => e.PaymentDate)
                .HasPrecision(0)
                .HasColumnName("payment_date");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.PostedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_payment_posted_at")
                .HasColumnName("posted_at");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.ReferenceNumber)
                .HasMaxLength(100)
                .HasColumnName("reference_number");
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("new", "df_payment_source")
                .HasColumnName("source");

            entity.HasOne(d => d.Client).WithMany(p => p.Payments)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_payment_client");

            entity.HasOne(d => d.Invoice).WithMany(p => p.Payments)
                .HasForeignKey(d => d.InvoiceId)
                .HasConstraintName("fk_payment_invoice");

            entity.HasOne(d => d.PaymentMethodNavigation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PaymentMethod)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_payment_payment_method");

            entity.HasOne(d => d.Practice).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_payment_practice");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.PaymentMethod1).HasName("pk_payment_method");

            entity.ToTable("payment_method");

            entity.Property(e => e.PaymentMethod1)
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("display_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_payment_method_is_active")
                .HasColumnName("is_active");
        });

        modelBuilder.Entity<Practice>(entity =>
        {
            entity.HasKey(e => e.PracticeId).HasName("pk_practice");

            entity.ToTable("practice");

            entity.Property(e => e.PracticeId)
                .HasDefaultValueSql("(newid())", "df_practice_practice_id")
                .HasColumnName("practice_id");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_practice_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_practice_is_active")
                .HasColumnName("is_active");
            entity.Property(e => e.PracticeName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("practice_name");
        });

        modelBuilder.Entity<Principal>(entity =>
        {
            entity.HasKey(e => e.PrincipalId).HasName("pk_principal");

            entity.ToTable("principal");

            entity.HasIndex(e => e.ClientId, "ix_principal_client_id");

            entity.Property(e => e.PrincipalId)
                .HasDefaultValueSql("(newid())", "df_principal_principal_id")
                .HasColumnName("principal_id");
            entity.Property(e => e.Active)
                .HasDefaultValue(true, "df_principal_active")
                .HasColumnName("active");
            entity.Property(e => e.Birthdate).HasColumnName("birthdate");
            entity.Property(e => e.Breed)
                .HasMaxLength(100)
                .HasColumnName("breed");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.ContextLabel)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("context_label");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_principal_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("display_name");
            entity.Property(e => e.Flags).HasColumnName("flags");
            entity.Property(e => e.LatestVisit)
                .HasPrecision(0)
                .HasColumnName("latest_visit");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.PreventiveFlags).HasColumnName("preventive_flags");
            entity.Property(e => e.Sex)
                .HasMaxLength(20)
                .HasColumnName("sex");
            entity.Property(e => e.Species)
                .HasMaxLength(100)
                .HasColumnName("species");

            entity.HasOne(d => d.Client).WithMany(p => p.Principals)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_principal_client");

            entity.HasOne(d => d.ContextLabelNavigation).WithMany(p => p.Principals)
                .HasForeignKey(d => d.ContextLabel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_principal_context_label");

            entity.HasOne(d => d.Practice).WithMany(p => p.Principals)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_principal_practice");
        });

        modelBuilder.Entity<PrincipalContextLabel>(entity =>
        {
            entity.HasKey(e => e.ContextLabel).HasName("pk_principal_context_label");

            entity.ToTable("principal_context_label");

            entity.Property(e => e.ContextLabel)
                .HasMaxLength(50)
                .HasColumnName("context_label");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("display_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_principal_context_label_is_active")
                .HasColumnName("is_active");
        });

        modelBuilder.Entity<PrincipalSummary>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("principal_summary");

            entity.Property(e => e.Active).HasColumnName("active");
            entity.Property(e => e.Birthdate).HasColumnName("birthdate");
            entity.Property(e => e.Breed)
                .HasMaxLength(100)
                .HasColumnName("breed");
            entity.Property(e => e.ClientAccountNumber)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("client_account_number");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.ClientName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("client_name");
            entity.Property(e => e.ContextLabel)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("context_label");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("display_name");
            entity.Property(e => e.Flags).HasColumnName("flags");
            entity.Property(e => e.LatestVisit)
                .HasPrecision(0)
                .HasColumnName("latest_visit");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.PreventiveFlags).HasColumnName("preventive_flags");
            entity.Property(e => e.PrincipalId).HasColumnName("principal_id");
            entity.Property(e => e.Sex)
                .HasMaxLength(20)
                .HasColumnName("sex");
            entity.Property(e => e.Species)
                .HasMaxLength(100)
                .HasColumnName("species");
        });

        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.ReservationId).HasName("pk_reservation");

            entity.ToTable("reservation");

            entity.HasIndex(e => new { e.ClientId, e.PrincipalId }, "ix_reservation_client_principal");

            entity.HasIndex(e => new { e.PracticeId, e.ArrivalDate }, "ix_reservation_practice_arrival_date");

            entity.Property(e => e.ReservationId)
                .HasDefaultValueSql("(newid())", "df_reservation_reservation_id")
                .HasColumnName("reservation_id");
            entity.Property(e => e.ArrivalDate)
                .HasPrecision(0)
                .HasColumnName("arrival_date");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.Comments)
                .HasMaxLength(2000)
                .HasColumnName("comments");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_reservation_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.EndingDate)
                .HasPrecision(0)
                .HasColumnName("ending_date");
            entity.Property(e => e.HospitalizedFlag).HasColumnName("hospitalized_flag");
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.PrincipalId).HasColumnName("principal_id");
            entity.Property(e => e.Source)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("new", "df_reservation_source")
                .HasColumnName("source");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.VisualStatusId).HasColumnName("visual_status_id");

            entity.HasOne(d => d.Client).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reservation_client");

            entity.HasOne(d => d.Practice).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reservation_practice");

            entity.HasOne(d => d.Principal).WithMany(p => p.Reservations)
                .HasForeignKey(d => d.PrincipalId)
                .HasConstraintName("fk_reservation_principal");

            entity.HasOne(d => d.Status).WithMany(p => p.ReservationStatuses)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reservation_status");

            entity.HasOne(d => d.VisualStatus).WithMany(p => p.ReservationVisualStatuses)
                .HasForeignKey(d => d.VisualStatusId)
                .HasConstraintName("fk_reservation_visual_status");
        });

        modelBuilder.Entity<ReservationStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("pk_reservation_status");

            entity.ToTable("reservation_status");

            entity.Property(e => e.StatusId)
                .HasDefaultValueSql("(newid())", "df_reservation_status_status_id")
                .HasColumnName("status_id");
            entity.Property(e => e.ColorCode)
                .HasMaxLength(20)
                .HasColumnName("color_code");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_reservation_status_is_active")
                .HasColumnName("is_active");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.SortOrder).HasColumnName("sort_order");
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("status_name");

            entity.HasOne(d => d.Practice).WithMany(p => p.ReservationStatuses)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_reservation_status_practice");
        });

        modelBuilder.Entity<Resource>(entity =>
        {
            entity.HasKey(e => e.ResourceId).HasName("pk_resource");

            entity.ToTable("resource");

            entity.HasIndex(e => new { e.PracticeId, e.ResourceType }, "ix_resource_practice_type");

            entity.Property(e => e.ResourceId)
                .HasDefaultValueSql("(newid())", "df_resource_resource_id")
                .HasColumnName("resource_id");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_resource_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_resource_is_active")
                .HasColumnName("is_active");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.ResourceName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("resource_name");
            entity.Property(e => e.ResourceType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("resource_type");

            entity.HasOne(d => d.Practice).WithMany(p => p.Resources)
                .HasForeignKey(d => d.PracticeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_resource_practice");

            entity.HasOne(d => d.ResourceTypeNavigation).WithMany(p => p.Resources)
                .HasForeignKey(d => d.ResourceType)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_resource_resource_type");
        });

        modelBuilder.Entity<ResourceType>(entity =>
        {
            entity.HasKey(e => e.ResourceType1).HasName("pk_resource_type");

            entity.ToTable("resource_type");

            entity.Property(e => e.ResourceType1)
                .HasMaxLength(50)
                .HasColumnName("resource_type");
            entity.Property(e => e.DisplayName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("display_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_resource_type_is_active")
                .HasColumnName("is_active");
        });

        modelBuilder.Entity<ScheduleBoard>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("schedule_board");

            entity.Property(e => e.AppointmentId).HasColumnName("appointment_id");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.Comments)
                .HasMaxLength(2000)
                .HasColumnName("comments");
            entity.Property(e => e.EndTime)
                .HasPrecision(0)
                .HasColumnName("end_time");
            entity.Property(e => e.GroupId).HasColumnName("group_id");
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");
            entity.Property(e => e.ItemType)
                .HasMaxLength(20)
                .HasColumnName("item_type");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.PrincipalId).HasColumnName("principal_id");
            entity.Property(e => e.RecurrenceId).HasColumnName("recurrence_id");
            entity.Property(e => e.ReservationId).HasColumnName("reservation_id");
            entity.Property(e => e.ResourceId).HasColumnName("resource_id");
            entity.Property(e => e.ResourceName)
                .HasMaxLength(200)
                .HasColumnName("resource_name");
            entity.Property(e => e.ResourceType)
                .HasMaxLength(50)
                .HasColumnName("resource_type");
            entity.Property(e => e.StartTime)
                .HasPrecision(0)
                .HasColumnName("start_time");
            entity.Property(e => e.StatusId).HasColumnName("status_id");
            entity.Property(e => e.StatusName)
                .HasMaxLength(100)
                .HasColumnName("status_name");
        });

        modelBuilder.Entity<UserPracticeAccess>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("user_practice_access");

            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .HasMaxLength(256)
                .HasColumnName("email");
            entity.Property(e => e.ExpiresAt)
                .HasPrecision(0)
                .HasColumnName("expires_at");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.IsEffectiveActive).HasColumnName("is_effective_active");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.PracticeName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("practice_name");
            entity.Property(e => e.RoleId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("role_id");
            entity.Property(e => e.RoleName)
                .HasMaxLength(256)
                .HasColumnName("role_name");
            entity.Property(e => e.RoleNormalizedName)
                .HasMaxLength(256)
                .HasColumnName("role_normalized_name");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("user_id");
            entity.Property(e => e.UserName)
                .HasMaxLength(256)
                .HasColumnName("user_name");
            entity.Property(e => e.UserPracticeRoleId).HasColumnName("user_practice_role_id");
        });

        modelBuilder.Entity<UserPracticeInvitation>(entity =>
        {
            entity.HasKey(e => e.UserPracticeInvitationId).HasName("pk_user_practice_invitation");

            entity.ToTable("user_practice_invitation");

            entity.HasIndex(e => new { e.NormalizedEmail, e.StatusName }, "ix_user_practice_invitation_email");

            entity.HasIndex(e => new { e.PracticeId, e.StatusName }, "ix_user_practice_invitation_practice_status");

            entity.HasIndex(e => e.InviteToken, "ix_user_practice_invitation_token").IsUnique();

            entity.Property(e => e.UserPracticeInvitationId)
                .HasDefaultValueSql("(newid())", "df_user_practice_invitation_id")
                .HasColumnName("user_practice_invitation_id");
            entity.Property(e => e.AcceptedAt)
                .HasPrecision(0)
                .HasColumnName("accepted_at");
            entity.Property(e => e.AcceptedUserId)
                .HasMaxLength(450)
                .HasColumnName("accepted_user_id");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_user_practice_invitation_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("email");
            entity.Property(e => e.ExpiresAt)
                .HasPrecision(0)
                .HasColumnName("expires_at");
            entity.Property(e => e.InviteToken)
                .HasDefaultValueSql("(newid())", "df_user_practice_invitation_token")
                .HasColumnName("invite_token");
            entity.Property(e => e.InvitedByUserId)
                .HasMaxLength(450)
                .HasColumnName("invited_by_user_id");
            entity.Property(e => e.NormalizedEmail)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("normalized_email");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.RevokedAt)
                .HasPrecision(0)
                .HasColumnName("revoked_at");
            entity.Property(e => e.RoleId)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("role_id");
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("pending", "df_user_practice_invitation_status")
                .HasColumnName("status_name");

            entity.HasOne(d => d.AcceptedUser).WithMany(p => p.UserPracticeInvitationAcceptedUsers)
                .HasForeignKey(d => d.AcceptedUserId)
                .HasConstraintName("fk_user_practice_invitation_accepted_user");

            entity.HasOne(d => d.InvitedByUser).WithMany(p => p.UserPracticeInvitationInvitedByUsers)
                .HasForeignKey(d => d.InvitedByUserId)
                .HasConstraintName("fk_user_practice_invitation_invited_by_user");

            entity.HasOne(d => d.Practice).WithMany(p => p.UserPracticeInvitations)
                .HasForeignKey(d => d.PracticeId)
                .HasConstraintName("fk_user_practice_invitation_practice");

            entity.HasOne(d => d.Role).WithMany(p => p.UserPracticeInvitations)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("fk_user_practice_invitation_role");
        });

        modelBuilder.Entity<UserPracticeRole>(entity =>
        {
            entity.HasKey(e => e.UserPracticeRoleId).HasName("pk_user_practice_role");

            entity.ToTable("user_practice_role");

            entity.HasIndex(e => new { e.PracticeId, e.RoleId }, "ix_user_practice_role_practice_role");

            entity.HasIndex(e => e.UserId, "ix_user_practice_role_user_id");

            entity.HasIndex(e => new { e.PracticeId, e.UserId, e.RoleId }, "uq_user_practice_role_practice_user_role").IsUnique();

            entity.Property(e => e.UserPracticeRoleId)
                .HasDefaultValueSql("(newid())", "df_user_practice_role_id")
                .HasColumnName("user_practice_role_id");
            entity.Property(e => e.CreatedAt)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysdatetime())", "df_user_practice_role_created_at")
                .HasColumnName("created_at");
            entity.Property(e => e.ExpiresAt)
                .HasPrecision(0)
                .HasColumnName("expires_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true, "df_user_practice_role_is_active")
                .HasColumnName("is_active");
            entity.Property(e => e.PracticeId).HasColumnName("practice_id");
            entity.Property(e => e.RoleId)
                .IsRequired()
                .HasColumnName("role_id");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasColumnName("user_id");

            entity.HasOne(d => d.Practice).WithMany(p => p.UserPracticeRoles)
                .HasForeignKey(d => d.PracticeId)
                .HasConstraintName("fk_user_practice_role_practice");

            entity.HasOne(d => d.Role).WithMany(p => p.UserPracticeRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("fk_user_practice_role_role");

            entity.HasOne(d => d.User).WithMany(p => p.UserPracticeRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_user_practice_role_user");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}