// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SlickSysDev.ApiService.Model;

public partial class UserPracticeInvitation : BaseEntity
{
    public Guid UserPracticeInvitationId { get; set; }

    public Guid PracticeId { get; set; }

    public string RoleId { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public Guid InviteToken { get; set; }

    public string StatusName { get; set; }

    public string InvitedByUserId { get; set; }

    public string AcceptedUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public DateTime? AcceptedAt { get; set; }

    public DateTime? RevokedAt { get; set; }

    public virtual AspNetUser AcceptedUser { get; set; }

    public virtual AspNetUser InvitedByUser { get; set; }

    public virtual Practice Practice { get; set; }

    public virtual AspNetRole Role { get; set; }
}