// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model;

public partial class UserPracticeAccess : BaseEntity
{
    public Guid UserPracticeRoleId { get; set; }

    public Guid PracticeId { get; set; }

    public string PracticeName { get; set; }

    public string UserId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public string RoleNormalizedName { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public bool? IsEffectiveActive { get; set; }
}