// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model
{
    public partial class usp_post_paymentResult : BaseEntity
    {
        public Guid payment_id { get; set; }
        public Guid practice_id { get; set; }
        public Guid client_id { get; set; }
        public Guid? invoice_id { get; set; }
        [Column("payment_amount", TypeName = "decimal(18,2)")]
        public decimal payment_amount { get; set; }
        public DateTime payment_date { get; set; }
        [StringLength(50)]
        public string payment_method { get; set; }
        [StringLength(100)]
        public string reference_number { get; set; }
        [StringLength(400)]
        public string memo { get; set; }
        [StringLength(50)]
        public string source { get; set; }
        public DateTime posted_at { get; set; }
    }
}
