// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model
{
    public partial class usp_add_user_practice_roleResult : BaseEntity
    {
        public Guid user_practice_role_id { get; set; }
        public Guid practice_id { get; set; }
        [StringLength(450)]
        public string user_id { get; set; }
        [StringLength(256)]
        public string role_name { get; set; }
        [StringLength(450)]
        public string role_id { get; set; }
        public bool is_active { get; set; }
        public DateTime created_at { get; set; }
        public DateTime? expires_at { get; set; }
    }
}
