// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model
{
    public partial class usp_create_reservationResult : BaseEntity
    {
        public Guid reservation_id { get; set; }
        public Guid practice_id { get; set; }
        public Guid client_id { get; set; }
        public Guid? principal_id { get; set; }
        public DateTime arrival_date { get; set; }
        public DateTime ending_date { get; set; }
        public Guid status_id { get; set; }
        public Guid? visual_status_id { get; set; }
        public bool hospitalized_flag { get; set; }
        [StringLength(2000)]
        public string comments { get; set; }
        [StringLength(50)]
        public string source { get; set; }
        public bool is_deleted { get; set; }
        public DateTime created_at { get; set; }
    }
}
