// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model
{
    public partial class usp_billing_summary_pagedResult : BaseEntity
    {
        public Guid practice_id { get; set; }
        public Guid client_id { get; set; }
        [StringLength(200)]
        public string client_name { get; set; }
        [Column("ar_current", TypeName = "decimal(38,2)")]
        public decimal? ar_current { get; set; }
        [Column("ar_30", TypeName = "decimal(38,2)")]
        public decimal? ar_30 { get; set; }
        [Column("ar_60", TypeName = "decimal(38,2)")]
        public decimal? ar_60 { get; set; }
        [Column("ar_90", TypeName = "decimal(38,2)")]
        public decimal? ar_90 { get; set; }
        [Column("total_due", TypeName = "decimal(38,2)")]
        public decimal? total_due { get; set; }
        [Column("credit_limit", TypeName = "decimal(18,2)")]
        public decimal credit_limit { get; set; }
        public DateTime? last_pay_date { get; set; }
        [Column("last_pay_amt", TypeName = "decimal(18,2)")]
        public decimal? last_pay_amt { get; set; }
        public int? open_invoice_count { get; set; }
        public int? recent_invoice_count { get; set; }
        [StringLength(8)]
        public string billing_status { get; set; }
    }
}
