// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model
{
    public partial class usp_principal_summary_pagedResult : BaseEntity
    {
        public Guid practice_id { get; set; }
        public Guid principal_id { get; set; }
        public Guid client_id { get; set; }
        [StringLength(20)]
        public string client_account_number { get; set; }
        [StringLength(200)]
        public string client_name { get; set; }
        [StringLength(200)]
        public string display_name { get; set; }
        [StringLength(50)]
        public string context_label { get; set; }
        [StringLength(100)]
        public string species { get; set; }
        [StringLength(100)]
        public string breed { get; set; }
        [StringLength(20)]
        public string sex { get; set; }
        public DateOnly? birthdate { get; set; }
        public bool active { get; set; }
        public DateTime? latest_visit { get; set; }
        [StringLength(2147483647)]
        public string flags { get; set; }
        [StringLength(2147483647)]
        public string preventive_flags { get; set; }
    }
}
