// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SlickSysDev.ApiService.Model
{
    public partial class usp_authorize_user_practiceResult : BaseEntity
    {
        public Guid? practice_id { get; set; }
        [StringLength(450)]
        public string user_id { get; set; }
        [StringLength(256)]
        public string required_role_name { get; set; }
        public bool? is_authorized { get; set; }
    }
}
