// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SlickSysDev.ApiService.Model
{
    public partial class usp_update_appointmentResult : BaseEntity
    {
        public Guid appointment_id { get; set; }
        public Guid practice_id { get; set; }
        public Guid client_id { get; set; }
        public Guid? principal_id { get; set; }
        public Guid? resource_id { get; set; }
        public Guid status_id { get; set; }
        public DateTime start_time { get; set; }
        public DateTime end_time { get; set; }
        [StringLength(2000)]
        public string comments { get; set; }
        public Guid? group_id { get; set; }
        public Guid? recurrence_id { get; set; }
        [StringLength(50)]
        public string source { get; set; }
        public bool is_deleted { get; set; }
        public DateTime created_at { get; set; }
    }
}
