// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SlickSysDev.ApiService.Model
{
    public partial class usp_practice_invitations_countResult : BaseEntity
    {
        public long? total_rows { get; set; }
    }
}
