// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model
{
    public partial class usp_schedule_board_pagedResult : BaseEntity
    {
        public Guid practice_id { get; set; }
        [StringLength(20)]
        public string item_type { get; set; }
        public Guid? appointment_id { get; set; }
        public Guid? reservation_id { get; set; }
        public Guid client_id { get; set; }
        public Guid? principal_id { get; set; }
        public Guid? resource_id { get; set; }
        [StringLength(200)]
        public string resource_name { get; set; }
        [StringLength(50)]
        public string resource_type { get; set; }
        public Guid status_id { get; set; }
        [StringLength(100)]
        public string status_name { get; set; }
        public DateTime start_time { get; set; }
        public DateTime end_time { get; set; }
        [StringLength(2000)]
        public string comments { get; set; }
        public Guid? group_id { get; set; }
        public Guid? recurrence_id { get; set; }
        public bool is_deleted { get; set; }
    }
}
