// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SlickSysDev.Data.Service;

namespace SlickSysDev.Data.Service.Model
{
    public partial class usp_accept_user_practice_invitationResult : BaseEntity
    {
        public Guid user_practice_invitation_id { get; set; }
        public Guid practice_id { get; set; }
        [StringLength(256)]
        public string email { get; set; }
        [StringLength(256)]
        public string normalized_email { get; set; }
        public Guid invite_token { get; set; }
        [StringLength(20)]
        public string status_name { get; set; }
        [StringLength(256)]
        public string role_name { get; set; }
        [StringLength(450)]
        public string role_id { get; set; }
        [StringLength(450)]
        public string invited_by_user_id { get; set; }
        [StringLength(450)]
        public string accepted_user_id { get; set; }
        public DateTime created_at { get; set; }
        public DateTime? expires_at { get; set; }
        public DateTime? accepted_at { get; set; }
        public DateTime? revoked_at { get; set; }
    }
}
