<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4bc89ad0-66d7-4bcb-9722-9fd3a8a2e1b9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlickSysDev.ApiService\SlickSysDev.ApiService.csproj" />
    <ProjectReference Include="..\SlickSysDev.Data.Api\ManagementData.Api.csproj" />
    <ProjectReference Include="..\SlickSysDev.Web\SlickSysDev.Web.csproj" />
    <ProjectReference Include="..\SlickSysDev.Admin\SlickSysDev.Admin.csproj" />
    <ProjectReference Include="..\SlickSysDev.Public\SlickSysDev.Public.csproj" />
  </ItemGroup>

</Project>
