<Project Sdk="Aspire.AppHost.Sdk/13.5.0-preview.1.26281.17">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4e161a9e-f5f5-4fa8-8130-9336e4e5519a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlickSysDev.Public\SlickSysDev.Public.csproj" />
    <ProjectReference Include="..\SlickSysDev.Admin\SlickSysDev.Admin.csproj" />
    <ProjectReference Include="..\SlickSysDev.ApiService\SlickSysDev.Data.Service.csproj" />
    <ProjectReference Include="..\SlickSysDev.Data.Api\SlickSysDev.DataApi.csproj" />
    <ProjectReference Include="..\SlickSysDev.Web\SlickSysDev.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.5.0-preview.1.26281.17" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.0-preview.1.26281.17" />
  </ItemGroup>

</Project>
