insert into [dbo].[payment] (
    [practice_id],
    [client_id],
    [invoice_id],
    [payment_amount],
    [payment_date],
    [payment_method],
    [reference_number],
    [memo],
    [source]
)
output
    inserted.[payment_id],
    inserted.[practice_id],
    inserted.[client_id],
    inserted.[invoice_id],
    inserted.[payment_amount],
    inserted.[payment_date],
    inserted.[payment_method],
    inserted.[reference_number],
    inserted.[memo],
    inserted.[source],
    inserted.[posted_at]
select
    @practice_id,
    @client_id,
    @invoice_id,
    @payment_amount,
    @payment_date,
    @payment_method,
    @reference_number,
    @memo,
    coalesce(@source, N'new');